services:
  - type: web
    name: videopro-backend
    env: python
    plan: free
    buildCommand: apt-get update && apt-get install -y ffmpeg && pip install -r gereksinimler.txt
    startCommand: uvicorn ana:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.8"
